### ISSUE TITLE
URLs are switched

### ISSUE THREAD

**Issue by ds2edv** [johanjanssen/AdoptOpenJDKChocolateyPackages#10]
Seems like URL32 and URL64 are switched in chocolateyinstall.ps1

**Comment by johanjanssen** [comment]
Hi @ds2edv, I've just created new packages with the script. This is in the installer of the package:
```
  Url = 'https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u262-b10/OpenJDK8U-jdk_x86-32_windows_hotspot_8u262b10.msi'
  Url64bit = 'https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u262-b10/OpenJDK8U-jdk_x64_windows_hotspot_8u262b10.msi'
```

So it looks like everything works fine. Did you experience any problems, or can you point to the specific part in the chocoinstall.ps1 file which you think is wrong?

**Comment by ds2edv** [comment]
Take a look at adoptopenjdkjre

Url = 'https://github.com/AdoptOpenJDK/openjdk14-binaries/releases/download/jdk-14.0.2%2B12/OpenJDK14U-jre_x64_windows_hotspot_14.0.2_12.msi' 

Url64bit = 'https://github.com/AdoptOpenJDK/openjdk14-binaries/releases/download/jdk-14.0.2%2B12/OpenJDK14U-jre_x86-32_windows_hotspot_14.0.2_12.msi'

**Comment by ds2edv** [comment]
@johanjanssen

**Comment by johanjanssen** [comment]
Ok apparently it differs per package. I'll go through all of them to check and fix it. Thanks a lot for submitting the issue @ds2edv !

**Comment by johanjanssen** [comment]
Managed to go through all packages and fix them where needed. New versions are uploaded @ds2edv , but it might take a while before they are verified and become available.

**Comment by johanjanssen** [comment]
@RedBaron2 apparently there was a bug in the scripts, which mixed up the 32 bit and 64 bit URL's and checksums.

I've checked and updated the broken packages by hand, see below. The mix up occurred for all versions except 8. Do you maybe want to fix it? As you probably know better how the scripts work :). No need to hurry, the next release is in September.

AdoptOpenJDK.14.0.2.12.nupkg broken
  Url = 'https://github.com/AdoptOpenJDK/openjdk14-binaries/releases/download/jdk-14.0.2%2B12/OpenJDK14U-jdk_x64_windows_hotspot_14.0.2_12.msi'
  Url64bit = 'https://github.com/AdoptOpenJDK/openjdk14-binaries/releases/download/jdk-14.0.2%2B12/OpenJDK14U-jdk_x86-32_windows_hotspot_14.0.2_12.msi'
  Checksum = '9CBD03600E58AD8D2383C15E596396FBDFBC9655BA0019F5BC74C910E4082C7C'
  ChecksumType = 'sha256'
  Checksum64 = '8DE52612E913BEB01641F84A0D6EC80D244853C3489116D9EC343ADB15DF80F7'
  ChecksumType64 = 'sha256'
  
  Url = 'https://github.com/AdoptOpenJDK/openjdk14-binaries/releases/download/jdk-14.0.2%2B12/OpenJDK14U-jdk_x86-32_windows_hotspot_14.0.2_12.msi'
  Url64bit = 'https://github.com/AdoptOpenJDK/openjdk14-binaries/releases/download/jdk-14.0.2%2B12/OpenJDK14U-jdk_x64_windows_hotspot_14.0.2_12.msi'
  Checksum = '8DE52612E913BEB01641F84A0D6EC80D244853C3489116D9EC343ADB15DF80F7'
  ChecksumType = 'sha256'
  Checksum64 = '9CBD03600E58AD8D2383C15E596396FBDFBC9655BA0019F5BC74C910E4082C7C'
  ChecksumType64 = 'sha256'
  
AdoptOpenJDK11.11.0.8.10.nupkg broken
  Url = 'https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.8%2B10/OpenJDK11U-jdk_x64_windows_hotspot_11.0.8_10.msi'
  Url64bit = 'https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.8%2B10/OpenJDK11U-jdk_x86-32_windows_hotspot_11.0.8_10.msi'
  Checksum = '148B487E0DDE39EC5C0F32AA2397C17968B6CF6818822CEA2B2394DFD0157396'
  ChecksumType = 'sha256'
  Checksum64 = '4150D41630885B7545EE04468C128EFC68D9AFAF08D00A7379CCDF5574E38E2F'
  ChecksumType64 = 'sha256'
  
  Url = 'https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.8%2B10/OpenJDK11U-jdk_x86-32_windows_hotspot_11.0.8_10.msi'
  Url64bit = 'https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.8%2B10/OpenJDK11U-jdk_x64_windows_hotspot_11.0.8_10.msi'
  Checksum = '4150D41630885B7545EE04468C128EFC68D9AFAF08D00A7379CCDF5574E38E2F'
  ChecksumType = 'sha256'
  Checksum64 = '148B487E0DDE39EC5C0F32AA2397C17968B6CF6818822CEA2B2394DFD0157396'
  ChecksumType64 = 'sha256'

AdoptOpenJDK11jre.11.0.8.10.nupkg broken

  Url = 'https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.8%2B10/OpenJDK11U-jre_x64_windows_hotspot_11.0.8_10.msi'
  Url64bit = 'https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.8%2B10/OpenJDK11U-jre_x86-32_windows_hotspot_11.0.8_10.msi'
  Checksum = 'C94202EEC5A406BF86352270CB0C9C17CB6C3FFC9C7D78C41E67B181E1D6F151'
  ChecksumType = 'sha256'
  Checksum64 = '1F5A39AC8B44A0C0F5E39DD5FD88DA81CD8A1DEB655EEA98191D6631137737E6'
  ChecksumType64 = 'sha256'
  
  Url = 'https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.8%2B10/OpenJDK11U-jre_x86-32_windows_hotspot_11.0.8_10.msi'
  Url64bit = 'https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.8%2B10/OpenJDK11U-jre_x64_windows_hotspot_11.0.8_10.msi'
  Checksum = '1F5A39AC8B44A0C0F5E39DD5FD88DA81CD8A1DEB655EEA98191D6631137737E6'
  ChecksumType = 'sha256'
  Checksum64 = 'C94202EEC5A406BF86352270CB0C9C17CB6C3FFC9C7D78C41E67B181E1D6F151'
  ChecksumType64 = 'sha256'  
  
  
AdoptOpenJDK11openj9.11.0.8.10.nupkg ok only 64 bit
AdoptOpenJDK11openj9jre.11.0.8.10.nupkg ok only 64 bit
AdoptOpenJDK14.14.0.2.12.nupkg broken

  Url = 'https://github.com/AdoptOpenJDK/openjdk14-binaries/releases/download/jdk-14.0.2%2B12/OpenJDK14U-jdk_x64_windows_hotspot_14.0.2_12.msi'
  Url64bit = 'https://github.com/AdoptOpenJDK/openjdk14-binaries/releases/download/jdk-14.0.2%2B12/OpenJDK14U-jdk_x86-32_windows_hotspot_14.0.2_12.msi'
  Checksum = '9CBD03600E58AD8D2383C15E596396FBDFBC9655BA0019F5BC74C910E4082C7C'
  ChecksumType = 'sha256'
  Checksum64 = '8DE52612E913BEB01641F84A0D6EC80D244853C3489116D9EC343ADB15DF80F7'
  ChecksumType64 = 'sha256'
  
  Url = 'https://github.com/AdoptOpenJDK/openjdk14-binaries/releases/download/jdk-14.0.2%2B12/OpenJDK14U-jdk_x86-32_windows_hotspot_14.0.2_12.msi'
  Url64bit = 'https://github.com/AdoptOpenJDK/openjdk14-binaries/releases/download/jdk-14.0.2%2B12/OpenJDK14U-jdk_x64_windows_hotspot_14.0.2_12.msi'
  Checksum = '8DE52612E913BEB01641F84A0D6EC80D244853C3489116D9EC343ADB15DF80F7'
  ChecksumType = 'sha256'
  Checksum64 = '9CBD03600E58AD8D2383C15E596396FBDFBC9655BA0019F5BC74C910E4082C7C'
  ChecksumType64 = 'sha256'
  
AdoptOpenJDK14jre.14.0.2.12.nupkg broken

  Url = ''
  Url64bit = 'https://github.com/AdoptOpenJDK/openjdk14-binaries/releases/download/jdk-14.0.2%2B12/OpenJDK14U-jre_x86-32_windows_hotspot_14.0.2_12.msi'
  Checksum = 'BF468C78387B8095914A2D46AF6961D5C22697929B66961E346A41FC8BF909D4'
  ChecksumType = 'sha256'
  Checksum64 = '63080DD3F509300ADD98F2B452AAD5CD2004A485E9DDEB7F326F8A8E931ADE3B'
  ChecksumType64 = 'sha256'
  
  Url = 'https://github.com/AdoptOpenJDK/openjdk14-binaries/releases/download/jdk-14.0.2%2B12/OpenJDK14U-jre_x86-32_windows_hotspot_14.0.2_12.msi'
  Url64bit = 'https://github.com/AdoptOpenJDK/openjdk14-binaries/releases/download/jdk-14.0.2%2B12/OpenJDK14U-jre_x64_windows_hotspot_14.0.2_12.msi'
  Checksum = '63080DD3F509300ADD98F2B452AAD5CD2004A485E9DDEB7F326F8A8E931ADE3B'
  ChecksumType = 'sha256'
  Checksum64 = 'BF468C78387B8095914A2D46AF6961D5C22697929B66961E346A41FC8BF909D4'
  ChecksumType64 = 'sha256'
  
AdoptOpenJDK14openj9.14.0.2.12.nupkg ok only 64 bit
AdoptOpenJDK14openj9jre.14.0.2.12.nupkg ok only 64 bit
AdoptOpenJDK8.8.262.10.nupkg ok
AdoptOpenJDK8jre.8.262.10.nupkg ok
AdoptOpenJDK8openj9.8.262.10.nupkg ok
AdoptOpenJDK8openj9jre.8.262.10.nupkg ok
AdoptOpenJDKjre.14.0.2.12.nupkg broken

  Url = 'https://github.com/AdoptOpenJDK/openjdk14-binaries/releases/download/jdk-14.0.2%2B12/OpenJDK14U-jre_x64_windows_hotspot_14.0.2_12.msi'
  Url64bit = 'https://github.com/AdoptOpenJDK/openjdk14-binaries/releases/download/jdk-14.0.2%2B12/OpenJDK14U-jre_x86-32_windows_hotspot_14.0.2_12.msi'
  Checksum = 'BF468C78387B8095914A2D46AF6961D5C22697929B66961E346A41FC8BF909D4'
  ChecksumType = 'sha256'
  Checksum64 = '63080DD3F509300ADD98F2B452AAD5CD2004A485E9DDEB7F326F8A8E931ADE3B'
  ChecksumType64 = 'sha256'
  
  Url = 'https://github.com/AdoptOpenJDK/openjdk14-binaries/releases/download/jdk-14.0.2%2B12/OpenJDK14U-jre_x86-32_windows_hotspot_14.0.2_12.msi'
  Url64bit = 'https://github.com/AdoptOpenJDK/openjdk14-binaries/releases/download/jdk-14.0.2%2B12/OpenJDK14U-jre_x64_windows_hotspot_14.0.2_12.msi'
  Checksum = '63080DD3F509300ADD98F2B452AAD5CD2004A485E9DDEB7F326F8A8E931ADE3B'
  ChecksumType = 'sha256'
  Checksum64 = 'BF468C78387B8095914A2D46AF6961D5C22697929B66961E346A41FC8BF909D4'
  ChecksumType64 = 'sha256'  

AdoptOpenJDKopenj9.14.0.2.12.nupkg ok only 64 bit
AdoptOpenJDKopenj9jre.14.0.2.12.nupkg ok only 64 bit

**Comment by ds2edv** [comment]
Nothing here to say thanks for. I just thought I should mention it.

@johanjanssen

**Comment by RedBaron2** [comment]
@johanjanssen 
Sorry about the mix-up. The API apparently changed how it returned data for all versions except for version 8. I have a patch that will fix the mix-up from happening again. I'll work on updating with a PR soon.

**Comment by johanjanssen** [comment]
@RedBaron2 no problem at all, things happen and if they changed the API you cannot do anything about it. Thanks a lot for working on the fix.

Out of curiosity, what did they exactly change in the API? Do we need to give them feedback about it? Maybe they're not aware of the difference. Or they plan to change it, which might break the scripts again.

**Comment by RedBaron2** [comment]
@johanjanssen 
They changed the order in which they sent in the links. It had always been URL 64 first then URL 32 last to be the opposite.
I updated the script to check for the link[0] to match x64, and to do the correct placement of the URL variables depending on the results.
