### ISSUE TITLE
FileType empty

### ISSUE THREAD

**Issue by johanjanssen** [johanjanssen/AdoptOpenJDKChocolateyPackages#13]
I've checked a few packages and it seems everywhere the fileType in the chocolateyinstall.ps1 is empty.

Problem:
`fileType = ''`

Example package
https://chocolatey.org/packages/adoptopenjdk (click download on the page)

Ping @RedBaron2 maybe something for you to look at :). You don't need to rush, it's not urgent. I've got the remark from the Chocolatey maintainers, they want to have it fixed in the next version of the package.

**Comment by RedBaron2** [comment]
@johanjanssen 
I noticed this when I was checking the `InstallDir` error. It will be addressed in that PR along with spacing issues in the coding.

**Comment by johanjanssen** [comment]
Fixed by @RedBaron2. Thanks a lot!
