### ISSUE TITLE
FeatureIcedTeaWeb and FeatureJNLPFileRunWith only available in AdoptOpenJDK 8

### ISSUE THREAD

**Issue by SuperVirus** [johanjanssen/AdoptOpenJDKChocolateyPackages#16]
Hi, 
the list of features for /ADDLOCAL= is not correct.
The features "FeatureIcedTeaWeb" and "FeatureJNLPFileRunWith" are only available in AdoptOpenJDK 8, but not in later versions.

For new AdoptOpenJDK 11 and newer [OpenWebStart](https://openwebstart.com/) can be used to get JNLP support.

**Comment by johanjanssen** [comment]
Hi @SuperVirus, thanks for the remark. I've just added some extra info: https://github.com/johanjanssen/AdoptOpenJDKChocolateyPackages/commit/0a31e34c60a6de5e576055749d445c8f253c2c61

**Comment by SuperVirus** [comment]
Hi @johanjanssen thank you for clarification. This could save some administrators a headache, as installation will fail if one of those features is requested.
