### ISSUE TITLE
Add options to installer

### ISSUE THREAD

**Issue by johanjanssen** [johanjanssen/AdoptOpenJDKChocolateyPackages#3]
The AdoptOpenJDK12 installer offers a variety of parameters for the installation, like "FeatureJavaHome" to update the JAVA_HOME environment variable or "FeatureOracleJavaSoft" to update the registry keys "HKLM\SOFTWARE\JavaSoft\".

Could you add these options to the Choco installer? Some software like MediathekView 3.30 require these values to be set in order to run with AdoptOpenJDK. If not set they complain that an JRE could not be found.

Installer options of AdoptOpenJDK: https://adoptopenjdk.net/installation.html?variant=openjdk12&jvmVariant=hotspot#

**Comment by RedBaron2** [comment]
@johanjanssen
How do you want to handle these parameters?
 • Just use the Install levels of 1, 2, or 3?
• Use of the feature options?
• Both of the above-mentioned ways?

The secondary question is what about the zip packages? The parameters can be similar but will be implemented very differently.

**Comment by johanjanssen-sanoma** [comment]
@RedBaron2 good question. I actually got this one from one  of the users. I think the feature options should be enough. The install levels just group them right? I think most users don't need these options at all, so a simple implementation based on the feature options is probably best.

Don't handle the zip packages, just use the MSI. There should be an MSI for all versions. They make installation, upgrades, removal lots easier. I also maintain some other builds with ZIP files and that's a lot more work. So if we don't need it, don't use zip files :).

**Comment by RedBaron2** [comment]
@johanjanssen 
Sounds good, but just for failsafe I will include `InstallLevel` just incase some user wants to use it later.

I do have another question about the use of 

> REINSTALLMODE options: (from [Control Events](https://www.advancedinstaller.com/user-guide/control-events.html))

I want to know if you have hear any feedback from any chocolatey users of the package about upgrades or reinstall issues?

It is coming along well so far. I should be able to start my testing sometime next week.

**Comment by johanjanssen-sanoma** [comment]
@RedBaron2 good to hear the changes are going well!

I don't think I got feedback on the upgrade/reinstalls of the MSI's, at least I don't remember it out of the top of my head. I think the MSI already works quite well, a lot better then the ZIP files :).

**Comment by RedBaron2** [comment]
@johanjanssen-sanoma 
If that be the case then I will not include `ReinstallMode` in the custom Package Parameters.

**Comment by johanjanssen** [comment]
Fixed by #6
