### ISSUE TITLE
Use the new AdoptOpenJDK v3 API

### ISSUE THREAD

**Issue by johanjanssen** [johanjanssen/AdoptOpenJDKChocolateyPackages#5]
See https://api.adoptopenjdk.net/

One of the new API's comes close to the response of the old one
https://api.adoptopenjdk.net/v3/assets/feature_releases/14/ga?architecture=x64&heap_size=normal&image_type=jdk&jvm_impl=hotspot&os=windows&page=0&page_size=1&project=jdk&sort_order=DESC

Leave out the architecture to get everything
https://api.adoptopenjdk.net/v3/assets/feature_releases/14/ga?heap_size=normal&image_type=jdk&jvm_impl=hotspot&os=windows&page=0&page_size=1&project=jdk&sort_order=DESC

**Comment by RedBaron2** [comment]
@johanjanssen 
Working on it. I should have a working function maybe by next week.

**Comment by johanjanssen** [comment]
@RedBaron2 cool, thanks a lot for working on it.

I don't know how much you're planning to change. But there is one other issue with the script. OpenJ9 except for Java 8 doesn't have 32 bit downloads. Now all the OpenJ9 packages except Java 8 have empty fields for the 32 bit download link, checksum and checksumtype. In case you're changing things in that part you might take that into account. Else we can look at it later.

**Comment by RedBaron2** [comment]
@johanjanssen-sanoma @johanjanssen 
The update script will now auto-change the chocolateyinstall file per the existence of a url32 variable
I have a question as to where you want the `.png` icon file located? 
It is almost ready for a run on appveyor soon.

**Comment by johanjanssen-sanoma** [comment]
@RedBaron2 next week updates are released for Java 8,11,13 then I could test your changes. But don't rush if it's not ready, it's no problem.

You can put the .png file in the which contains the update script.

**Comment by johanjanssen** [comment]
@RedBaron2 I've released the current AdoptOpenJDK packages with your scripts. Thanks a lot.

Fixed by PR: #6
